# Generated by Django 3.2.7 on 2022-03-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='toto',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
