# Generated by Django 3.2.7 on 2022-03-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_toto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='toto',
        ),
    ]
